---

  - name: Get variables file
    include_vars: variables.yml

  - name: Install Nginx
    package:
     name: nginx
     state: present

  - name: Install rsync
    package:
     name: rsync
     state: present
  
  - name: Ensure Nginx service is enabled 
    service:
      name: nginx
      enabled: yes
      state: started

  - name: Create www directory
    file:
      path: "/var/www/{{ domain }}"
      state: directory
      mode: '0775'

  - name: Remove default site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx

  - name: "sync website"
    synchronize:
      src: site/
      dest: "/var/www/{{ domain }}"
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no

